// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

guint gladesharp_glade_idallocator_get_n_words_offset (void);

guint
gladesharp_glade_idallocator_get_n_words_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeIDAllocator, n_words);
}

guint gladesharp_glade_idallocator_get_data_offset (void);

guint
gladesharp_glade_idallocator_get_data_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeIDAllocator, data);
}

guint gladesharp_glade_menueditor_get_icon_widget_offset (void);

guint
gladesharp_glade_menueditor_get_icon_widget_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, icon_widget);
}

guint gladesharp_glade_menueditor_get_label_label_offset (void);

guint
gladesharp_glade_menueditor_get_label_label_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, label_label);
}

guint gladesharp_glade_menueditor_get_add_button_offset (void);

guint
gladesharp_glade_menueditor_get_add_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, add_button);
}

guint gladesharp_glade_menueditor_get_stock_combo_offset (void);

guint
gladesharp_glade_menueditor_get_stock_combo_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, stock_combo);
}

guint gladesharp_glade_menueditor_get_clist_offset (void);

guint
gladesharp_glade_menueditor_get_clist_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, clist);
}

guint gladesharp_glade_menueditor_get_accel_alt_checkbutton_offset (void);

guint
gladesharp_glade_menueditor_get_accel_alt_checkbutton_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, accel_alt_checkbutton);
}

guint gladesharp_glade_menueditor_get_updating_widgets_offset (void);

guint
gladesharp_glade_menueditor_get_updating_widgets_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, updating_widgets);
}

guint gladesharp_glade_menueditor_get_radio_radiobutton_offset (void);

guint
gladesharp_glade_menueditor_get_radio_radiobutton_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, radio_radiobutton);
}

guint gladesharp_glade_menueditor_get_delete_button_offset (void);

guint
gladesharp_glade_menueditor_get_delete_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, delete_button);
}

guint gladesharp_glade_menueditor_get_normal_radiobutton_offset (void);

guint
gladesharp_glade_menueditor_get_normal_radiobutton_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, normal_radiobutton);
}

guint gladesharp_glade_menueditor_get_tooltip_entry_offset (void);

guint
gladesharp_glade_menueditor_get_tooltip_entry_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, tooltip_entry);
}

guint gladesharp_glade_menueditor_get_group_label_offset (void);

guint
gladesharp_glade_menueditor_get_group_label_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, group_label);
}

guint gladesharp_glade_menueditor_get_check_radiobutton_offset (void);

guint
gladesharp_glade_menueditor_get_check_radiobutton_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, check_radiobutton);
}

guint gladesharp_glade_menueditor_get_apply_button_offset (void);

guint
gladesharp_glade_menueditor_get_apply_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, apply_button);
}

guint gladesharp_glade_menueditor_get_name_entry_offset (void);

guint
gladesharp_glade_menueditor_get_name_entry_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, name_entry);
}

guint gladesharp_glade_menueditor_get_tooltip_label_offset (void);

guint
gladesharp_glade_menueditor_get_tooltip_label_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, tooltip_label);
}

guint gladesharp_glade_menueditor_get_window_offset (void);

guint
gladesharp_glade_menueditor_get_window_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, window);
}

guint gladesharp_glade_menueditor_get_ok_button_offset (void);

guint
gladesharp_glade_menueditor_get_ok_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, ok_button);
}

guint gladesharp_glade_menueditor_get_label_entry_offset (void);

guint
gladesharp_glade_menueditor_get_label_entry_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, label_entry);
}

guint gladesharp_glade_menueditor_get_keys_dialog_offset (void);

guint
gladesharp_glade_menueditor_get_keys_dialog_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, keys_dialog);
}

guint gladesharp_glade_menueditor_get_handler_label_offset (void);

guint
gladesharp_glade_menueditor_get_handler_label_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, handler_label);
}

guint gladesharp_glade_menueditor_get_icon_button_offset (void);

guint
gladesharp_glade_menueditor_get_icon_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, icon_button);
}

guint gladesharp_glade_menueditor_get_handler_entry_offset (void);

guint
gladesharp_glade_menueditor_get_handler_entry_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, handler_entry);
}

guint gladesharp_glade_menueditor_get_right_justify_label_offset (void);

guint
gladesharp_glade_menueditor_get_right_justify_label_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, right_justify_label);
}

guint gladesharp_glade_menueditor_get_state_label_offset (void);

guint
gladesharp_glade_menueditor_get_state_label_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, state_label);
}

guint gladesharp_glade_menueditor_get_stock_label_offset (void);

guint
gladesharp_glade_menueditor_get_stock_label_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, stock_label);
}

guint gladesharp_glade_menueditor_get_left_button_offset (void);

guint
gladesharp_glade_menueditor_get_left_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, left_button);
}

guint gladesharp_glade_menueditor_get_add_separator_button_offset (void);

guint
gladesharp_glade_menueditor_get_add_separator_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, add_separator_button);
}

guint gladesharp_glade_menueditor_get_up_button_offset (void);

guint
gladesharp_glade_menueditor_get_up_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, up_button);
}

guint gladesharp_glade_menueditor_get_state_togglebutton_offset (void);

guint
gladesharp_glade_menueditor_get_state_togglebutton_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, state_togglebutton);
}

guint gladesharp_glade_menueditor_get_stock_items_offset (void);

guint
gladesharp_glade_menueditor_get_stock_items_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, stock_items);
}

guint gladesharp_glade_menueditor_get_type_frame_offset (void);

guint
gladesharp_glade_menueditor_get_type_frame_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, type_frame);
}

guint gladesharp_glade_menueditor_get_accel_ctrl_checkbutton_offset (void);

guint
gladesharp_glade_menueditor_get_accel_ctrl_checkbutton_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, accel_ctrl_checkbutton);
}

guint gladesharp_glade_menueditor_get_project_offset (void);

guint
gladesharp_glade_menueditor_get_project_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, project);
}

guint gladesharp_glade_menueditor_get_down_button_offset (void);

guint
gladesharp_glade_menueditor_get_down_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, down_button);
}

guint gladesharp_glade_menueditor_get_accel_key_entry_offset (void);

guint
gladesharp_glade_menueditor_get_accel_key_entry_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, accel_key_entry);
}

guint gladesharp_glade_menueditor_get_accel_frame_offset (void);

guint
gladesharp_glade_menueditor_get_accel_frame_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, accel_frame);
}

guint gladesharp_glade_menueditor_get_menu_offset (void);

guint
gladesharp_glade_menueditor_get_menu_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, menu);
}

guint gladesharp_glade_menueditor_get_group_combo_offset (void);

guint
gladesharp_glade_menueditor_get_group_combo_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, group_combo);
}

guint gladesharp_glade_menueditor_get_gnome_support_offset (void);

guint
gladesharp_glade_menueditor_get_gnome_support_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, gnome_support);
}

guint gladesharp_glade_menueditor_get_accel_shift_checkbutton_offset (void);

guint
gladesharp_glade_menueditor_get_accel_shift_checkbutton_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, accel_shift_checkbutton);
}

guint gladesharp_glade_menueditor_get_add_child_button_offset (void);

guint
gladesharp_glade_menueditor_get_add_child_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, add_child_button);
}

guint gladesharp_glade_menueditor_get_right_button_offset (void);

guint
gladesharp_glade_menueditor_get_right_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, right_button);
}

guint gladesharp_glade_menueditor_get_cancel_button_offset (void);

guint
gladesharp_glade_menueditor_get_cancel_button_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, cancel_button);
}

guint gladesharp_glade_menueditor_get_right_justify_togglebutton_offset (void);

guint
gladesharp_glade_menueditor_get_right_justify_togglebutton_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, right_justify_togglebutton);
}

guint gladesharp_glade_menueditor_get_name_label_offset (void);

guint
gladesharp_glade_menueditor_get_name_label_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, name_label);
}

guint gladesharp_glade_menueditor_get_icon_label_offset (void);

guint
gladesharp_glade_menueditor_get_icon_label_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, icon_label);
}

guint gladesharp_glade_menueditor_get_menu_destroy_handler_id_offset (void);

guint
gladesharp_glade_menueditor_get_menu_destroy_handler_id_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeMenuEditor, menu_destroy_handler_id);
}

guint gladesharp_glade_parameter_get_value_offset (void);

guint
gladesharp_glade_parameter_get_value_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeParameter, value);
}

guint gladesharp_glade_parameter_get_key_offset (void);

guint
gladesharp_glade_parameter_get_key_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeParameter, key);
}

guint gladesharp_glade_signal_get_after_offset (void);

guint
gladesharp_glade_signal_get_after_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeSignal, after);
}

guint gladesharp_glade_signal_get_lookup_offset (void);

guint
gladesharp_glade_signal_get_lookup_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeSignal, lookup);
}

guint gladesharp_glade_signal_get_userdata_offset (void);

guint
gladesharp_glade_signal_get_userdata_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeSignal, userdata);
}

guint gladesharp_glade_signal_get_handler_offset (void);

guint
gladesharp_glade_signal_get_handler_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeSignal, handler);
}

guint gladesharp_glade_signal_get_name_offset (void);

guint
gladesharp_glade_signal_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeSignal, name);
}

gboolean gladesharp_glade_signalinfo_get_after (GladeSignalInfo *signalinfo);
void gladesharp_glade_signalinfo_set_after (GladeSignalInfo *signalinfo, gboolean value);

gboolean
gladesharp_glade_signalinfo_get_after (GladeSignalInfo *signalinfo)
{
	return (gboolean)signalinfo->after;
}

void
gladesharp_glade_signalinfo_set_after (GladeSignalInfo *signalinfo, gboolean value)
{
	signalinfo->after = (gboolean)value;
}

gboolean gladesharp_glade_signalinfo_get_lookup (GladeSignalInfo *signalinfo);
void gladesharp_glade_signalinfo_set_lookup (GladeSignalInfo *signalinfo, gboolean value);

gboolean
gladesharp_glade_signalinfo_get_lookup (GladeSignalInfo *signalinfo)
{
	return (gboolean)signalinfo->lookup;
}

void
gladesharp_glade_signalinfo_set_lookup (GladeSignalInfo *signalinfo, gboolean value)
{
	signalinfo->lookup = (gboolean)value;
}

