// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

#include <glade.h>

guint gladeuisharp_gladeui_propertyclass_get_packing_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_packing_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, packing);
}

guint gladeuisharp_gladeui_propertyclass_get_pspec_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_pspec_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, pspec);
}

guint gladeuisharp_gladeui_propertyclass_get_ignore_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_ignore_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, ignore);
}

guint gladeuisharp_gladeui_propertyclass_get_name_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, name);
}

guint gladeuisharp_gladeui_propertyclass_get_displayable_values_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_displayable_values_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, displayable_values);
}

guint gladeuisharp_gladeui_propertyclass_get_orig_def_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_orig_def_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, orig_def);
}

guint gladeuisharp_gladeui_propertyclass_get_parameters_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_parameters_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, parameters);
}

guint gladeuisharp_gladeui_propertyclass_get_optional_default_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_optional_default_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, optional_default);
}

guint gladeuisharp_gladeui_propertyclass_get_optional_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_optional_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, optional);
}

guint gladeuisharp_gladeui_propertyclass_get_query_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_query_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, query);
}

guint gladeuisharp_gladeui_propertyclass_get_save_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_save_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, save);
}

guint gladeuisharp_gladeui_propertyclass_get_construct_only_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_construct_only_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, construct_only);
}

guint gladeuisharp_gladeui_propertyclass_get_is_modified_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_is_modified_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, is_modified);
}

guint gladeuisharp_gladeui_propertyclass_get_def_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_def_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, def);
}

guint gladeuisharp_gladeui_propertyclass_get_visible_lines_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_visible_lines_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, visible_lines);
}

guint gladeuisharp_gladeui_propertyclass_get_tooltip_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_tooltip_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, tooltip);
}

guint gladeuisharp_gladeui_propertyclass_get_common_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_common_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, common);
}

guint gladeuisharp_gladeui_propertyclass_get_id_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_id_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, id);
}

guint gladeuisharp_gladeui_propertyclass_get_translatable_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_translatable_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, translatable);
}

guint gladeuisharp_gladeui_propertyclass_get_visible_offset (void);

guint
gladeuisharp_gladeui_propertyclass_get_visible_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladePropertyClass, visible);
}

gboolean gladeuisharp_gladeui_signalinfo_get_after (GladeSignalInfo *signalinfo);
void gladeuisharp_gladeui_signalinfo_set_after (GladeSignalInfo *signalinfo, gboolean value);

gboolean
gladeuisharp_gladeui_signalinfo_get_after (GladeSignalInfo *signalinfo)
{
	return (gboolean)signalinfo->after;
}

void
gladeuisharp_gladeui_signalinfo_set_after (GladeSignalInfo *signalinfo, gboolean value)
{
	signalinfo->after = (gboolean)value;
}

gboolean gladeuisharp_gladeui_signalinfo_get_lookup (GladeSignalInfo *signalinfo);
void gladeuisharp_gladeui_signalinfo_set_lookup (GladeSignalInfo *signalinfo, gboolean value);

gboolean
gladeuisharp_gladeui_signalinfo_get_lookup (GladeSignalInfo *signalinfo)
{
	return (gboolean)signalinfo->lookup;
}

void
gladeuisharp_gladeui_signalinfo_set_lookup (GladeSignalInfo *signalinfo, gboolean value)
{
	signalinfo->lookup = (gboolean)value;
}

guint gladeuisharp_gladeui_widgetclass_get_signals_offset (void);

guint
gladeuisharp_gladeui_widgetclass_get_signals_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeWidgetClass, signals);
}

guint gladeuisharp_gladeui_widgetclass_get_icon_offset (void);

guint
gladeuisharp_gladeui_widgetclass_get_icon_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeWidgetClass, icon);
}

guint gladeuisharp_gladeui_widgetclass_get_name_offset (void);

guint
gladeuisharp_gladeui_widgetclass_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeWidgetClass, name);
}

guint gladeuisharp_gladeui_widgetclass_get_children_offset (void);

guint
gladeuisharp_gladeui_widgetclass_get_children_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeWidgetClass, children);
}

guint gladeuisharp_gladeui_widgetclass_get_generic_name_offset (void);

guint
gladeuisharp_gladeui_widgetclass_get_generic_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeWidgetClass, generic_name);
}

guint gladeuisharp_gladeui_widgetclass_get_properties_offset (void);

guint
gladeuisharp_gladeui_widgetclass_get_properties_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeWidgetClass, properties);
}

guint gladeuisharp_gladeui_widgetclass_get_palette_name_offset (void);

guint
gladeuisharp_gladeui_widgetclass_get_palette_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeWidgetClass, palette_name);
}

guint gladeuisharp_gladeui_widgetclass_get_in_palette_offset (void);

guint
gladeuisharp_gladeui_widgetclass_get_in_palette_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeWidgetClass, in_palette);
}

guint gladeuisharp_gladeui_widgetclass_get_child_packings_offset (void);

guint
gladeuisharp_gladeui_widgetclass_get_child_packings_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeWidgetClass, child_packings);
}

guint gladeuisharp_gladeui_widgetclass_get_type_offset (void);

guint
gladeuisharp_gladeui_widgetclass_get_type_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GladeWidgetClass, type);
}

